name: update

on:
  issue_comment

jobs:
  update:
    name: "update"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: "Checkout the other repository 🛎"
        uses: actions/checkout@v4
        with:
          path: code_repo
          repository: 'kcpevey/gh_actions_playground_code'

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
            #   Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
            # Required, if the artifact is from a different repo
            # Required, if the repo is private a Personal Access Token with `repo` scope is needed or GitHub token in a job where the permissions `action` scope set to `read`
            github_token: ${{secrets.GITHUB_TOKEN}}
            # Optional, workflow file name or ID
            # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
            workflow: on_pr.yml
            # Optional, the status or conclusion of a completed workflow to search for
            # Can be one of a workflow conclusion:
            #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
            # Or a workflow status:
            #   "completed", "in_progress", "queued"
            # Use the empty string ("") to ignore status or conclusion in the search
            workflow_conclusion: success
            # Optional, defaults to all types
            event: push
            # Optional, will use specified workflow run
            # use ${{ github.event.workflow_run.id }} when your action runs in a workflow_run event
            # Optional, defaults to current repo
            repo: ${{ github.repository }}
            # Optional, choose how to exit the action if no artifact is found
            if_no_artifact_found: fail
        

      - name: "Copy images to other repo"
        run: |
            ls
            cp filename code_repo/.

      - name: "Create PR to conda-store with updated images"
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: update_images
          delete-branch: true
          title: '[AUTO] Update images'
          body: |
            Update images
            - Updated with the latest images from playwright
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request

